# Generated by Django 3.1.4 on 2021-10-14 12:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[200, 200], upload_to='Menu Images'),
        ),
    ]
